controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    use_sim_time: true

    left_wheel_names: ["left_wheeL_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.40
    wheel_radius: 0.10

    base_frame_id: body_link
    odom_frame_id: odom
    enable_odom_tf: true
    publish_rate: 50.0

    use_stamped_vel: false
    cmd_vel_timeout: 0.5

    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 1.6
    linear.x.min_velocity: -1.6
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 1.5
    linear.x.min_acceleration: -1.5

    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 6.0
    angular.z.min_acceleration: -6.0
