controller_manager:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

wheel_effort_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - left_wheeL_joint
      - right_wheel_joint
    interface_name: effort
